'use strict';

// tests/incidentRecoveryCalibration.test.js
//
// B-3 M1 — Current-Path Incident-Recovery Mechanics Characterization &
// Integrity-Under-Fault Validation.
//
// PURPOSE (binding scope — read before editing):
//   This file measures, against actual PostgreSQL 17, how the CURRENT
//   evidence-repository read/write path behaves when a harness-owned,
//   test-controlled fault is injected and then clears. It produces:
//     1. a recovery-mechanics characterization under declared synthetic
//        conditions,
//     2. a fault/recovery integrity validation against actual PostgreSQL,
//     3. measured engineering facts that MAY later inform an Operations
//        risk-policy decision.
//
//   It does NOT discover, select, or bound an owner RETRY_COUNT or
//   RECOVERY_WINDOW, does NOT prove owner-policy adequacy, and does NOT
//   prove harness determinism or a real-world recovery-time distribution.
//   Every retry/backoff parameter used below is a HARNESS-OWNED
//   EXPERIMENTAL INPUT to this calibration run only. See
//   tests/incidentRecoveryCalibrationHarness.js for the same binding note.
//
//   RETRY_COUNT and RECOVERY_WINDOW remain:
//     OWNER_VALUE_UNSET / OWNER JUDGMENT STILL REQUIRED
//
// FAULT SCOPE — implemented in this file:
//   FAMILY 1        transient DB read failure
//   FAMILY 2        transient DB write / transaction failure
//   FAMILY 3        DB connection/backend unavailable then restored
//   FAMILY 5        duplicate logical attempt / idempotency interaction
//   FAMILY 6        missing / technical-failure classification integrity
//   FAMILY 7-NARROW raw-evidence integrity verification after recovery
//
// Explicitly DEFERRED (not implemented here):
//   FAMILY 4        cascade_jobs worker/job processing
//   FAMILY 7-FULL   generalized metric/recomputation
//
// All fault injection lives in this file and in
// tests/incidentRecoveryCalibrationHarness.js only. No production file is
// read, written, or modified. No migration is added. No production
// retry/backoff/timer, test hook, worker, generalized metric module, or
// resource/cost ledger is introduced.
//
// Ephemeral evidence packages are written to stdout (JSONL) and to a
// Windows-TEMP JSONL file (see harness `createEpisodeSink`). Nothing is
// persisted to PostgreSQL and nothing generated by this file is committed.

const { test, describe, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { pool } = require('../db/pool');
const { runMigrations } = require('../db/migrate');
const evidence = require('../src/instrumentation');
const harness = require('./incidentRecoveryCalibrationHarness');

const repository = evidence.evidenceRepository;

// ---------------------------------------------------------------------------
// Declared harness inputs — held IDENTICAL across both full-matrix
// executions in the repeatability smoke check below. Experimental inputs
// only; not owner policy.
// ---------------------------------------------------------------------------

const HARNESS_INPUTS = Object.freeze({
  maxAttempts: 3,
  spacingMs: 30,
  cadenceMode: 'FIXED',
  family3FaultDurationMs: 40,
});

const FIXTURE_SCALE = Object.freeze({
  grammarNodesPerRun: 2,
  participantsPerRun: 1,
  enrollmentsPerRun: 1,
  assignmentsPerRun: 5,
  sessionsPerRun: 4,
});

// ---------------------------------------------------------------------------
// Generic helpers
// ---------------------------------------------------------------------------

async function countRows(queryable, table, whereSql, params) {
  const { rows } = await queryable.query(
    `SELECT count(*) AS n FROM ${table}${whereSql ? ` WHERE ${whereSql}` : ''}`,
    params
  );
  return Number(rows[0].n);
}

const REQUIRED_EPISODE_KEYS = [
  'failure_family',
  'affected_scope',
  'attempt_id',
  'session_id',
  'assignment_id',
  'fault_duration_ms',
  'healthy_at',
  'retry_attempt_spacing_ms',
  'recovery_attempt_ordinal',
  'recovery_attempt_at',
  'recovery_succeeded',
  'error_class',
  'recovery_detection_latency_ms',
  'integrity_verification_latency_ms',
  'integrity_verification_result',
  'duplicate_detected',
  'contamination_detected',
  'missing_ambiguity_detected',
  'diagnostic',
];

function buildEpisode(fields) {
  for (const key of REQUIRED_EPISODE_KEYS) {
    if (!Object.prototype.hasOwnProperty.call(fields, key)) {
      throw new Error(`incident-recovery episode is missing required field: ${key}`);
    }
  }
  const diagnosticRequired = [
    'retry_cadence_mode',
    'fault_recoverability_state_by_attempt',
    'injected_fault_start',
    'first_recovery_attempt_at',
    'integrity_verification_start_at',
    'integrity_verified_at',
    'fixture_scale',
    'integrity_check_set',
  ];
  for (const key of diagnosticRequired) {
    if (!Object.prototype.hasOwnProperty.call(fields.diagnostic, key)) {
      throw new Error(`incident-recovery episode diagnostic metadata is missing: ${key}`);
    }
  }
  return fields;
}

function classificationOf(episode) {
  // Only the fields that repeatability compares — integrity classifications,
  // never timings. Matching values across two independently executed
  // full-matrix runs is observed repeatability for THOSE executions only.
  return {
    failure_family: episode.failure_family,
    integrity_verification_result: episode.integrity_verification_result,
    duplicate_detected: episode.duplicate_detected,
    contamination_detected: episode.contamination_detected,
    missing_ambiguity_detected: episode.missing_ambiguity_detected,
  };
}

// F1 correction: asserts that the harness-configured fault actually fired,
// derived from the recovery trace AND the fault counter's own observation
// log — not merely inferred from final-state success. Without this, a
// future SQL/matcher drift could make injection silently non-firing while
// the surrounding final-state assertions kept passing on an unfaulted path.
function assertFaultFired(trace, counter, expectedInjectedCount, context) {
  const injectedObservations = counter.attempts.filter((observation) => observation.injectedFailure);
  assert.equal(
    injectedObservations.length,
    expectedInjectedCount,
    `${context}: expected exactly ${expectedInjectedCount} harness-injected failure(s) to have actually ` +
      `fired (observed ${injectedObservations.length}) — this is the fault-injection matcher no longer ` +
      'matching its target SQL, not a recovery-behavior finding'
  );
  const injectedTraceEntry = trace.find(
    (entry) => entry.recovery_succeeded === false
      && entry.error_class === 'HARNESS_INJECTED_TRANSIENT_FAILURE'
  );
  assert.ok(
    injectedTraceEntry,
    `${context}: recovery trace contains no attempt whose failure was the harness-injected fault`
  );
  return injectedObservations.length;
}

function rubricDefinition(prefix, nodeA, nodeB) {
  return {
    definitionType: 'EVIDENCE_ERROR_CLASSIFICATION_RUBRIC',
    definitionVersion: 1,
    scoreMode: 'BINARY',
    classificationVocabulary: [
      'NO_ERROR',
      'LINGUISTIC_ERROR',
      'TASK_INSTRUCTION_MISUNDERSTANDING',
      'MODALITY_INPUT_FAILURE',
      'NO_EVALUABLE_RESPONSE',
      'UNCLASSIFIED',
    ],
    linguisticCategoryVocabulary: ['FORM', 'WORD_ORDER', 'LEXICAL_CHOICE', 'OTHER'],
    attributionRelationVocabulary: ['TARGET', 'PREREQUISITE', 'CONTRAST', 'UNRESOLVED'],
    rubricRuleIds: [`${prefix}_RULE_NO_ERROR`],
    attributionAuthority: {
      byTargetNode: {
        [nodeA]: { prerequisiteNodeIds: [nodeB], contrastNodeIds: [nodeB] },
        [nodeB]: { prerequisiteNodeIds: [nodeA], contrastNodeIds: [nodeA] },
      },
    },
  };
}

function instrumentationDefinition() {
  return {
    definitionType: 'EVIDENCE_INSTRUMENTATION_PROTOCOL',
    definitionVersion: 1,
    timingPolicy: {
      collectionProfile: 'FULL',
      durationConsistencyToleranceMs: 5,
      durationMismatchBehavior: 'REJECT',
    },
    correctionCoverageMode: 'COMPLETE_BUCKET_SET',
    responseBounds: {
      textMaxUtf8Bytes: 65536,
      referenceMaxUtf8Bytes: 2048,
      jsonMaxUtf8Bytes: 65536,
    },
    modalityPolicy: {
      allowedStimulusModalities: ['TEXT', 'AUDIO', 'IMAGE', 'VIDEO'],
      allowedResponseModalities: ['TEXT_ENTRY', 'SELECTION', 'STRUCTURED_ACTION', 'SPEECH'],
      stimulusCoverage: 'EXACT_PLANNED',
      responseCoverage: 'EXACT_PLANNED',
    },
  };
}

function correctionBuckets(count = 0) {
  const rows = [];
  for (const initiator of ['LEARNER', 'SYSTEM']) {
    for (const feedbackPhase of ['PRE_FEEDBACK', 'POST_FEEDBACK']) {
      for (const correctionOutcome of ['SUCCESSFUL', 'UNSUCCESSFUL', 'UNKNOWN']) {
        rows.push({ initiator, feedbackPhase, correctionOutcome, count });
      }
    }
  }
  return rows;
}

function noErrorEvaluation(nodeId, ruleId) {
  return {
    nodeId,
    rubricOutcome: {
      classification: 'NO_ERROR',
      linguisticCategory: null,
      attributionRelation: null,
      attributedNodeId: null,
      rubricRuleId: ruleId,
    },
    isCorrect: true,
  };
}

// ---------------------------------------------------------------------------
// Fixture setup — one authority fixture (experiment/condition/references/
// grammar nodes/participant/enrollment) per matrix run, uniquely prefixed so
// two matrix runs in one process never collide.
// ---------------------------------------------------------------------------

async function registerReference(prefix, kind, suffix, version, definition) {
  const referenceId = `${prefix}_${suffix}`;
  await repository.registerReferenceVersion(pool, {
    referenceKind: kind,
    referenceId,
    version,
    definition: definition ?? { kind, referenceId, version },
  });
  return referenceId;
}

async function setupAuthorityFixture(prefix) {
  const nodeA = `${prefix}_NODE_A`;
  const nodeB = `${prefix}_NODE_B`;
  await pool.query(
    `INSERT INTO grammar_nodes (node_id, language, concept_ids, label, difficulty)
     VALUES ($1, 'VI', '[]'::jsonb, $2, 1), ($3, 'VI', '[]'::jsonb, $4, 1)`,
    [nodeA, `${prefix} Node A`, nodeB, `${prefix} Node B`]
  );

  const experimentId = `${prefix}_EXP`;
  const conditionId = `${prefix}_COND`;
  await repository.registerExperimentVersion(pool, {
    experimentId,
    version: 1,
    definition: { protocol: 'B3_M1_CALIBRATION' },
  });
  await repository.registerConditionVersion(pool, {
    conditionId,
    version: 1,
    conditionClass: 'ENGINEERING_BASELINE',
    definition: { mode: 'FIXED' },
  });

  const ruleId = `${prefix}_RULE_NO_ERROR`;
  const itemId = await registerReference(prefix, 'ITEM', 'ITEM', 1);
  const scenarioId = await registerReference(prefix, 'SCENARIO', 'SCEN', 1);
  const itemFamilyId = await registerReference(prefix, 'ITEM_FAMILY', 'FAM', 1);
  const lexicalManifestId = await registerReference(prefix, 'LEXICAL_MANIFEST', 'LEX', 1);
  const rubricId = await registerReference(
    prefix,
    'RUBRIC',
    'RUBRIC',
    1,
    rubricDefinition(prefix, nodeA, nodeB)
  );
  const formulaId = await registerReference(prefix, 'FORMULA', 'FORM', 1);
  const schedulerProtocolId = await registerReference(prefix, 'SCHEDULER_PROTOCOL', 'SCHED', 1);
  const instrumentationProtocolId = await registerReference(
    prefix,
    'INSTRUMENTATION_PROTOCOL',
    'INSTR',
    1,
    instrumentationDefinition()
  );

  const participant = await repository.createParticipant(pool, {});
  const enrollment = await repository.createEnrollment(pool, {
    participantId: participant.participant_id,
    experimentId,
    experimentVersion: 1,
    conditionId,
    conditionVersion: 1,
  });

  const references = {
    itemId,
    itemVersion: 1,
    scenarioId,
    scenarioVersion: 1,
    itemFamilyId,
    itemFamilyVersion: 1,
    lexicalManifestId,
    lexicalManifestVersion: 1,
    rubricId,
    rubricVersion: 1,
    formulaId,
    formulaVersion: 1,
    schedulerProtocolId,
    schedulerProtocolVersion: 1,
    instrumentationProtocolId,
    instrumentationProtocolVersion: 1,
  };

  return { enrollment, references, nodeA, nodeB, ruleId };
}

async function createFixtureAssignment(fixture, overrides = {}) {
  return repository.createAssignment(pool, {
    enrollmentId: fixture.enrollment.enrollment_id,
    assignmentType: 'ASSESSMENT',
    targetTimepoint: 'IMMEDIATE',
    anchorStrategy: 'NODE_ASSIGNMENT_COMPLETION',
    targetNodeIds: [fixture.nodeA, fixture.nodeB],
    references: { ...fixture.references },
    plannedStimulusModalities: ['TEXT'],
    plannedResponseModalities: ['TEXT_ENTRY'],
    ...overrides,
  });
}

// ---------------------------------------------------------------------------
// FAMILY 1 — transient DB read failure
// ---------------------------------------------------------------------------

async function runFamily1(fixture, prefix) {
  const assignment = await createFixtureAssignment(fixture);
  const assignmentId = assignment.assignment.assignment_id;

  const injectedFaultStartMs = harness.nowMs();
  const injectedFaultStart = harness.isoNow();
  const counter = harness.createFaultCounter(2);
  const faultyPool = harness.wrapPoolWithFaults(pool, {
    matcher: /^SELECT \* FROM evidence_assignments WHERE assignment_id/i,
    counter,
  });

  const { result, trace } = await harness.runWithHarnessRecovery({
    operation: () => repository.getAssignmentAggregate(faultyPool, assignmentId),
    maxAttempts: HARNESS_INPUTS.maxAttempts,
    spacingMs: HARNESS_INPUTS.spacingMs,
    cadenceMode: HARNESS_INPUTS.cadenceMode,
  });

  const firstSuccess = trace.find((entry) => entry.recovery_succeeded);
  const healthyAtMs = firstSuccess.recovery_attempt_at_ms;

  const verificationStart = harness.isoNow();
  const verificationStartMs = harness.nowMs();
  const { rows: directRows } = await pool.query(
    'SELECT assignment_id, terminal_outcome FROM evidence_assignments WHERE assignment_id = $1',
    [assignmentId]
  );
  const integrityPass = Boolean(
    result
    && result.assignment
    && directRows[0]
    && result.assignment.assignment_id === directRows[0].assignment_id
    && result.assignment.terminal_outcome === directRows[0].terminal_outcome
  );
  const verificationEnd = harness.isoNow();
  const verificationEndMs = harness.nowMs();

  harness.assertCausalOrder([
    { name: 'injected_fault_start', value: injectedFaultStartMs },
    { name: 'first_recovery_attempt_at', value: trace[0].recovery_attempt_at_ms },
    { name: 'healthy_at', value: healthyAtMs },
    { name: 'integrity_verification_start_at', value: verificationStartMs },
    { name: 'integrity_verified_at', value: verificationEndMs },
  ]);

  return buildEpisode({
    failure_family: 'FAMILY_1_TRANSIENT_READ',
    affected_scope: 'evidence_assignments read via getAssignmentAggregate',
    attempt_id: null,
    session_id: null,
    assignment_id: assignmentId,
    fault_duration_ms: 0,
    healthy_at: new Date(healthyAtMs).toISOString(),
    retry_attempt_spacing_ms: HARNESS_INPUTS.spacingMs,
    recovery_attempt_ordinal: trace.length,
    recovery_attempt_at: trace.map((e) => e.recovery_attempt_at),
    recovery_succeeded: true,
    error_class: trace[0].error_class,
    recovery_detection_latency_ms: healthyAtMs - injectedFaultStartMs,
    integrity_verification_latency_ms: verificationEndMs - verificationStartMs,
    integrity_verification_result: integrityPass ? 'PASS' : 'FAIL',
    duplicate_detected: false,
    contamination_detected: false,
    missing_ambiguity_detected: false,
    diagnostic: {
      retry_cadence_mode: HARNESS_INPUTS.cadenceMode,
      fault_recoverability_state_by_attempt: trace.map((e) => e.fault_recoverability_state),
      injected_fault_start: injectedFaultStart,
      first_recovery_attempt_at: trace[0].recovery_attempt_at,
      integrity_verification_start_at: verificationStart,
      integrity_verified_at: verificationEnd,
      fixture_scale: FIXTURE_SCALE,
      integrity_check_set: ['recomputed_read_matches_direct_read'],
      total_recovery_elapsed_ms: verificationEndMs - injectedFaultStartMs,
      fault_counter_observations: counter.attempts,
      matrix_prefix: prefix,
    },
  });
}

// ---------------------------------------------------------------------------
// FAMILY 2 — transient DB write / transaction failure
// ---------------------------------------------------------------------------

async function runFamily2(fixture, prefix) {
  const assignment = await createFixtureAssignment(fixture);
  const assignmentId = assignment.assignment.assignment_id;
  const session = await repository.startSession(pool, {
    enrollmentId: fixture.enrollment.enrollment_id,
  });
  const attempt = await repository.openAttempt(pool, {
    assignmentId,
    sessionId: session.session_id,
    idempotencyIdentity: `${prefix}-f2-open`,
    instrumentationProtocolId: fixture.references.instrumentationProtocolId,
    instrumentationProtocolVersion: 1,
    openPayload: { family: 'FAMILY_2' },
  });

  const injectedFaultStartMs = harness.nowMs();
  const injectedFaultStart = harness.isoNow();
  const counter = harness.createFaultCounter(1);
  const faultyPool = harness.wrapPoolWithFaults(pool, {
    matcher: /INSERT\s+INTO\s+evidence_attempt_finalizations\b/i,
    counter,
  });

  const finalizationInput = {
    attemptId: attempt.attemptId,
    finalizationIdempotencyIdentity: `${prefix}-f2-final`,
    instrumentationProtocolId: fixture.references.instrumentationProtocolId,
    instrumentationProtocolVersion: 1,
    responseKind: 'TEXT',
    responseText: 'incident-recovery-calibration response',
    inputEnabledOffsetMs: 100,
    firstValidActivityOffsetMs: 120,
    submittedOffsetMs: 200,
    reportedClientMonotonicDurationMs: 100,
    actualStimulusModalities: ['TEXT'],
    actualResponseModalities: ['TEXT_ENTRY'],
    evaluations: [
      noErrorEvaluation(fixture.nodeA, fixture.ruleId),
      noErrorEvaluation(fixture.nodeB, fixture.ruleId),
    ],
    correctionAggregates: correctionBuckets(0),
  };

  const { trace } = await harness.runWithHarnessRecovery({
    operation: () => repository.finalizeAttempt(faultyPool, finalizationInput),
    maxAttempts: HARNESS_INPUTS.maxAttempts,
    spacingMs: HARNESS_INPUTS.spacingMs,
    cadenceMode: HARNESS_INPUTS.cadenceMode,
  });

  const firstSuccess = trace.find((entry) => entry.recovery_succeeded);
  const healthyAtMs = firstSuccess.recovery_attempt_at_ms;
  const faultFiredCount = assertFaultFired(trace, counter, 1, 'FAMILY_2');

  const verificationStart = harness.isoNow();
  const verificationStartMs = harness.nowMs();
  // Rollback-correctness check: evidence_attempt_finalizations.attempt_id is
  // the PRIMARY KEY. If the transaction that failed mid-way (after the
  // harness-injected error on the INSERT) had NOT been fully rolled back,
  // the retry's own INSERT for the same attempt_id would hit a duplicate-key
  // (23505) constraint violation instead of succeeding. Reaching exactly one
  // row here is therefore real, not fabricated, evidence of rollback
  // correctness under an actual PostgreSQL transaction.
  const finalizationCount = await countRows(
    pool,
    'evidence_attempt_finalizations',
    'attempt_id = $1',
    [attempt.attemptId]
  );
  const evaluationCount = await countRows(
    pool,
    'evidence_target_node_evaluations',
    'attempt_id = $1',
    [attempt.attemptId]
  );
  const integrityPass = finalizationCount === 1 && evaluationCount === 2;
  const verificationEnd = harness.isoNow();
  const verificationEndMs = harness.nowMs();

  harness.assertCausalOrder([
    { name: 'injected_fault_start', value: injectedFaultStartMs },
    { name: 'first_recovery_attempt_at', value: trace[0].recovery_attempt_at_ms },
    { name: 'healthy_at', value: healthyAtMs },
    { name: 'integrity_verification_start_at', value: verificationStartMs },
    { name: 'integrity_verified_at', value: verificationEndMs },
  ]);

  return {
    episode: buildEpisode({
      failure_family: 'FAMILY_2_TRANSIENT_WRITE',
      affected_scope: 'evidence_attempt_finalizations insert via finalizeAttempt',
      attempt_id: attempt.attemptId,
      session_id: session.session_id,
      assignment_id: assignmentId,
      fault_duration_ms: 0,
      healthy_at: new Date(healthyAtMs).toISOString(),
      retry_attempt_spacing_ms: HARNESS_INPUTS.spacingMs,
      recovery_attempt_ordinal: trace.length,
      recovery_attempt_at: trace.map((e) => e.recovery_attempt_at),
      recovery_succeeded: true,
      error_class: trace[0].error_class,
      recovery_detection_latency_ms: healthyAtMs - injectedFaultStartMs,
      integrity_verification_latency_ms: verificationEndMs - verificationStartMs,
      integrity_verification_result: integrityPass ? 'PASS' : 'FAIL',
      duplicate_detected: false,
      contamination_detected: finalizationCount !== 1,
      missing_ambiguity_detected: false,
      diagnostic: {
        retry_cadence_mode: HARNESS_INPUTS.cadenceMode,
        fault_recoverability_state_by_attempt: trace.map((e) => e.fault_recoverability_state),
        injected_fault_start: injectedFaultStart,
        first_recovery_attempt_at: trace[0].recovery_attempt_at,
        integrity_verification_start_at: verificationStart,
        integrity_verified_at: verificationEnd,
        fixture_scale: FIXTURE_SCALE,
        integrity_check_set: [
          'finalization_row_count_equals_one_after_rollback_and_retry',
          'evaluation_row_count_equals_target_node_count',
        ],
        total_recovery_elapsed_ms: verificationEndMs - injectedFaultStartMs,
        fault_counter_observations: counter.attempts,
        fault_fired_count: faultFiredCount,
        matrix_prefix: prefix,
      },
    }),
    attemptId: attempt.attemptId,
    assignmentId,
    sessionId: session.session_id,
  };
}

// ---------------------------------------------------------------------------
// FAMILY 3 — DB connection/backend unavailable then restored
// ---------------------------------------------------------------------------

async function runFamily3(prefix) {
  const injectedFaultStartMs = harness.nowMs();
  const injectedFaultStart = harness.isoNow();

  const { client: isolatedClient, pid: originalPid } = await harness.openIsolatedClient();
  await isolatedClient.query('SELECT 1 AS ok');

  const terminated = await harness.terminateIsolatedBackend(pool, originalPid);
  assert.equal(terminated, true, 'harness-owned isolated backend must be terminable');

  // Declared harness input: simulate an outage window before reconnection is
  // attempted. This is the fault_duration_ms for this family — a real,
  // declared wait, not a synthetic counter.
  await harness.sleep(HARNESS_INPUTS.family3FaultDurationMs);

  let workingClient = isolatedClient;
  let reconnectedPid = null;
  const { trace } = await harness.runWithHarnessRecovery({
    operation: async () => {
      try {
        await workingClient.query('SELECT 1 AS ok');
        return workingClient;
      } catch (error) {
        workingClient = harness.newIsolatedClient();
        await workingClient.connect();
        throw error;
      }
    },
    maxAttempts: HARNESS_INPUTS.maxAttempts,
    spacingMs: HARNESS_INPUTS.spacingMs,
    cadenceMode: HARNESS_INPUTS.cadenceMode,
  });

  const firstSuccess = trace.find((entry) => entry.recovery_succeeded);
  const healthyAtMs = firstSuccess.recovery_attempt_at_ms;

  const verificationStart = harness.isoNow();
  const verificationStartMs = harness.nowMs();
  const { rows: pidRows } = await workingClient.query('SELECT pg_backend_pid() AS pid');
  const { rows: dbRows } = await workingClient.query('SELECT current_database() AS db');
  reconnectedPid = pidRows[0].pid;
  // F5 correction: the expected database identity is derived from the
  // shared, already-healthy db/pool.js connection itself — a live trusted
  // reference — rather than from process.env.PGDATABASE. Comparing against
  // an unset env var would silently pass (undefined === undefined) if
  // PGDATABASE were ever absent from the environment; comparing two live
  // connections' own reported identity cannot silently degrade that way.
  const { rows: trustedDbRows } = await pool.query('SELECT current_database() AS db');
  const expectedDatabase = trustedDbRows[0].db;
  const integrityPass = reconnectedPid !== originalPid && dbRows[0].db === expectedDatabase;
  const verificationEnd = harness.isoNow();
  const verificationEndMs = harness.nowMs();

  await workingClient.end();
  if (workingClient !== isolatedClient) {
    try {
      await isolatedClient.end();
    } catch {
      // Already terminated by pg_terminate_backend; end() on a dead
      // connection is a harmless no-op-equivalent cleanup attempt.
    }
  }

  harness.assertCausalOrder([
    { name: 'injected_fault_start', value: injectedFaultStartMs },
    { name: 'first_recovery_attempt_at', value: trace[0].recovery_attempt_at_ms },
    { name: 'healthy_at', value: healthyAtMs },
    { name: 'integrity_verification_start_at', value: verificationStartMs },
    { name: 'integrity_verified_at', value: verificationEndMs },
  ]);

  return buildEpisode({
    failure_family: 'FAMILY_3_CONNECTION_UNAVAILABLE_THEN_RESTORED',
    affected_scope: 'isolated harness-owned PostgreSQL backend (pg_terminate_backend + reconnect)',
    attempt_id: null,
    session_id: null,
    assignment_id: null,
    fault_duration_ms: HARNESS_INPUTS.family3FaultDurationMs,
    healthy_at: new Date(healthyAtMs).toISOString(),
    retry_attempt_spacing_ms: HARNESS_INPUTS.spacingMs,
    recovery_attempt_ordinal: trace.length,
    recovery_attempt_at: trace.map((e) => e.recovery_attempt_at),
    recovery_succeeded: true,
    error_class: trace[0].error_class,
    recovery_detection_latency_ms: healthyAtMs - injectedFaultStartMs,
    integrity_verification_latency_ms: verificationEndMs - verificationStartMs,
    integrity_verification_result: integrityPass ? 'PASS' : 'FAIL',
    duplicate_detected: false,
    contamination_detected: false,
    missing_ambiguity_detected: false,
    diagnostic: {
      retry_cadence_mode: HARNESS_INPUTS.cadenceMode,
      fault_recoverability_state_by_attempt: trace.map((e) => e.fault_recoverability_state),
      injected_fault_start: injectedFaultStart,
      first_recovery_attempt_at: trace[0].recovery_attempt_at,
      integrity_verification_start_at: verificationStart,
      integrity_verified_at: verificationEnd,
      fixture_scale: FIXTURE_SCALE,
      integrity_check_set: [
        'reconnected_backend_pid_differs_from_terminated_pid',
        'reconnected_client_reports_expected_database',
      ],
      total_recovery_elapsed_ms: verificationEndMs - injectedFaultStartMs,
      original_pid: originalPid,
      reconnected_pid: reconnectedPid,
      expected_database: expectedDatabase,
      matrix_prefix: prefix,
    },
  });
}

// ---------------------------------------------------------------------------
// FAMILY 5 — duplicate logical attempt / idempotency interaction
// ---------------------------------------------------------------------------

async function runFamily5(fixture, prefix) {
  const assignment = await createFixtureAssignment(fixture);
  const assignmentId = assignment.assignment.assignment_id;
  const session = await repository.startSession(pool, {
    enrollmentId: fixture.enrollment.enrollment_id,
  });
  const idempotencyIdentity = `${prefix}-f5-dup`;
  const openPayload = { family: 'FAMILY_5', mode: 'DUP_TEST' };

  const injectedFaultStartMs = harness.nowMs();
  const injectedFaultStart = harness.isoNow();
  const counter = harness.createFaultCounter(1);
  const faultyPool = harness.wrapPoolWithFaults(pool, {
    matcher: /INSERT\s+INTO\s+evidence_attempts\b/i,
    counter,
  });

  const openInput = {
    assignmentId,
    sessionId: session.session_id,
    idempotencyIdentity,
    instrumentationProtocolId: fixture.references.instrumentationProtocolId,
    instrumentationProtocolVersion: 1,
    openPayload,
  };

  const { result: firstOpen, trace } = await harness.runWithHarnessRecovery({
    operation: () => repository.openAttempt(faultyPool, openInput),
    maxAttempts: HARNESS_INPUTS.maxAttempts,
    spacingMs: HARNESS_INPUTS.spacingMs,
    cadenceMode: HARNESS_INPUTS.cadenceMode,
  });
  const firstSuccess = trace.find((entry) => entry.recovery_succeeded);
  const healthyAtMs = firstSuccess.recovery_attempt_at_ms;
  const faultFiredCount = assertFaultFired(trace, counter, 1, 'FAMILY_5');

  const verificationStart = harness.isoNow();
  const verificationStartMs = harness.nowMs();

  // Genuine duplicate logical attempt submission (real pool, no fault):
  // identical idempotency identity + identical payload must replay the
  // existing attempt rather than create a second row.
  const replayOpen = await repository.openAttempt(pool, openInput);
  const rowCountAfterReplay = await countRows(
    pool,
    'evidence_attempts',
    'assignment_id = $1 AND idempotency_identity = $2',
    [assignmentId, idempotencyIdentity]
  );

  // Conflicting duplicate: same identity, different payload must be
  // rejected, not silently accepted and not corrupting the existing row.
  let conflictRejected = false;
  try {
    await repository.openAttempt(pool, {
      ...openInput,
      openPayload: { family: 'FAMILY_5', mode: 'DUP_TEST_CONFLICT' },
    });
  } catch (error) {
    conflictRejected = error?.code === 'CONTRACT_VIOLATION';
  }
  const rowCountAfterConflict = await countRows(
    pool,
    'evidence_attempts',
    'assignment_id = $1 AND idempotency_identity = $2',
    [assignmentId, idempotencyIdentity]
  );

  const duplicateDetected = replayOpen.replayed === true
    && replayOpen.attemptId === firstOpen.attemptId;
  const integrityPass = duplicateDetected
    && rowCountAfterReplay === 1
    && conflictRejected
    && rowCountAfterConflict === 1;

  const verificationEnd = harness.isoNow();
  const verificationEndMs = harness.nowMs();

  harness.assertCausalOrder([
    { name: 'injected_fault_start', value: injectedFaultStartMs },
    { name: 'first_recovery_attempt_at', value: trace[0].recovery_attempt_at_ms },
    { name: 'healthy_at', value: healthyAtMs },
    { name: 'integrity_verification_start_at', value: verificationStartMs },
    { name: 'integrity_verified_at', value: verificationEndMs },
  ]);

  return {
    episode: buildEpisode({
      failure_family: 'FAMILY_5_DUPLICATE_IDEMPOTENCY_INTERACTION',
      affected_scope: 'evidence_attempts insert via openAttempt (harness retry + genuine duplicate submission)',
      attempt_id: firstOpen.attemptId,
      session_id: session.session_id,
      assignment_id: assignmentId,
      fault_duration_ms: 0,
      healthy_at: new Date(healthyAtMs).toISOString(),
      retry_attempt_spacing_ms: HARNESS_INPUTS.spacingMs,
      recovery_attempt_ordinal: trace.length,
      recovery_attempt_at: trace.map((e) => e.recovery_attempt_at),
      recovery_succeeded: true,
      error_class: trace[0].error_class,
      recovery_detection_latency_ms: healthyAtMs - injectedFaultStartMs,
      integrity_verification_latency_ms: verificationEndMs - verificationStartMs,
      integrity_verification_result: integrityPass ? 'PASS' : 'FAIL',
      duplicate_detected: duplicateDetected,
      contamination_detected: rowCountAfterReplay !== 1 || rowCountAfterConflict !== 1,
      missing_ambiguity_detected: false,
      diagnostic: {
        retry_cadence_mode: HARNESS_INPUTS.cadenceMode,
        fault_recoverability_state_by_attempt: trace.map((e) => e.fault_recoverability_state),
        injected_fault_start: injectedFaultStart,
        first_recovery_attempt_at: trace[0].recovery_attempt_at,
        integrity_verification_start_at: verificationStart,
        integrity_verified_at: verificationEnd,
        fixture_scale: FIXTURE_SCALE,
        integrity_check_set: [
          'replay_returns_same_attempt_id',
          'row_count_stays_one_after_replay',
          'conflicting_payload_rejected_as_contract_violation',
          'row_count_stays_one_after_rejected_conflict',
        ],
        total_recovery_elapsed_ms: verificationEndMs - injectedFaultStartMs,
        fault_counter_observations: counter.attempts,
        fault_fired_count: faultFiredCount,
        matrix_prefix: prefix,
      },
    }),
    attemptId: firstOpen.attemptId,
    assignmentId,
    sessionId: session.session_id,
  };
}

// ---------------------------------------------------------------------------
// FAMILY 6 — missing / technical-failure classification integrity
// ---------------------------------------------------------------------------

async function runFamily6(fixture, prefix) {
  const missingAssignment = await createFixtureAssignment(fixture);
  const missingAssignmentId = missingAssignment.assignment.assignment_id;
  const techFailureAssignment = await createFixtureAssignment(fixture);
  const techFailureAssignmentId = techFailureAssignment.assignment.assignment_id;

  // F6 correction: assignment-level MISSING / TECHNICAL_FAILURE are
  // constructed directly here (raw SQL) because no repository API currently
  // derives those assignment terminal states — evidenceRepository.js
  // exposes no assignment-terminal-state setter beyond finalizeAttempt's
  // COMPLETED path. This is NOT the same pattern as
  // tests/evidenceFoundationRepository.test.js's own direct-SQL fixtures
  // (those construct ENROLLMENT status — a different table and column;
  // there is no existing assignment-level precedent to point to). Both
  // values below ARE schema-valid members of the real
  // evidence_assignments_outcome_check CHECK constraint enforced by actual
  // PostgreSQL, so this fixture exercises a state the live schema genuinely
  // allows. FAMILY 6's scope is classification-STATE READ-BACK / integrity
  // under fault — not production classification derivation: no engine or
  // repository code decided these outcomes here, the harness set them.
  await pool.query(
    `UPDATE evidence_assignments SET terminal_outcome = 'MISSING' WHERE assignment_id = $1`,
    [missingAssignmentId]
  );
  await pool.query(
    `UPDATE evidence_assignments SET terminal_outcome = 'TECHNICAL_FAILURE' WHERE assignment_id = $1`,
    [techFailureAssignmentId]
  );

  const techFailureSession = await repository.startSession(pool, {
    enrollmentId: fixture.enrollment.enrollment_id,
  });
  await repository.terminalizeSession(pool, {
    sessionId: techFailureSession.session_id,
    terminalOutcome: 'TECHNICAL_FAILURE',
    technicalFailureRef: `${prefix}-B3-M1-TECH-FAILURE-REF`,
  });

  const injectedFaultStartMs = harness.nowMs();
  const injectedFaultStart = harness.isoNow();
  const counter = harness.createFaultCounter(1);
  const faultyPool = harness.wrapPoolWithFaults(pool, {
    matcher: /^SELECT assignment_id, terminal_outcome FROM evidence_assignments WHERE assignment_id = ANY/i,
    counter,
  });

  const { result, trace } = await harness.runWithHarnessRecovery({
    operation: () => faultyPool.query(
      'SELECT assignment_id, terminal_outcome FROM evidence_assignments WHERE assignment_id = ANY($1)',
      [[missingAssignmentId, techFailureAssignmentId]]
    ),
    maxAttempts: HARNESS_INPUTS.maxAttempts,
    spacingMs: HARNESS_INPUTS.spacingMs,
    cadenceMode: HARNESS_INPUTS.cadenceMode,
  });
  const firstSuccess = trace.find((entry) => entry.recovery_succeeded);
  const healthyAtMs = firstSuccess.recovery_attempt_at_ms;
  const faultFiredCount = assertFaultFired(trace, counter, 1, 'FAMILY_6');

  const verificationStart = harness.isoNow();
  const verificationStartMs = harness.nowMs();
  const byId = new Map(result.rows.map((row) => [row.assignment_id, row.terminal_outcome]));
  const { rows: sessionRows } = await pool.query(
    'SELECT terminal_outcome, technical_failure_ref FROM evidence_sessions WHERE session_id = $1',
    [techFailureSession.session_id]
  );

  const missingCorrect = byId.get(missingAssignmentId) === 'MISSING';
  const techFailureCorrect = byId.get(techFailureAssignmentId) === 'TECHNICAL_FAILURE';
  const sessionCorrect = sessionRows[0].terminal_outcome === 'TECHNICAL_FAILURE'
    && sessionRows[0].technical_failure_ref === `${prefix}-B3-M1-TECH-FAILURE-REF`;
  const ambiguityDetected = !missingCorrect || !techFailureCorrect || !sessionCorrect;
  const integrityPass = !ambiguityDetected;
  const verificationEnd = harness.isoNow();
  const verificationEndMs = harness.nowMs();

  harness.assertCausalOrder([
    { name: 'injected_fault_start', value: injectedFaultStartMs },
    { name: 'first_recovery_attempt_at', value: trace[0].recovery_attempt_at_ms },
    { name: 'healthy_at', value: healthyAtMs },
    { name: 'integrity_verification_start_at', value: verificationStartMs },
    { name: 'integrity_verified_at', value: verificationEndMs },
  ]);

  return {
    episode: buildEpisode({
      failure_family: 'FAMILY_6_MISSING_VS_TECHNICAL_FAILURE_CLASSIFICATION',
      affected_scope: 'evidence_assignments.terminal_outcome + evidence_sessions.terminal_outcome read-back',
      attempt_id: null,
      session_id: techFailureSession.session_id,
      assignment_id: missingAssignmentId,
      fault_duration_ms: 0,
      healthy_at: new Date(healthyAtMs).toISOString(),
      retry_attempt_spacing_ms: HARNESS_INPUTS.spacingMs,
      recovery_attempt_ordinal: trace.length,
      recovery_attempt_at: trace.map((e) => e.recovery_attempt_at),
      recovery_succeeded: true,
      error_class: trace[0].error_class,
      recovery_detection_latency_ms: healthyAtMs - injectedFaultStartMs,
      integrity_verification_latency_ms: verificationEndMs - verificationStartMs,
      integrity_verification_result: integrityPass ? 'PASS' : 'FAIL',
      duplicate_detected: false,
      contamination_detected: false,
      missing_ambiguity_detected: ambiguityDetected,
      diagnostic: {
        retry_cadence_mode: HARNESS_INPUTS.cadenceMode,
        fault_recoverability_state_by_attempt: trace.map((e) => e.fault_recoverability_state),
        injected_fault_start: injectedFaultStart,
        first_recovery_attempt_at: trace[0].recovery_attempt_at,
        integrity_verification_start_at: verificationStart,
        integrity_verified_at: verificationEnd,
        fixture_scale: FIXTURE_SCALE,
        integrity_check_set: [
          'missing_assignment_reads_back_as_missing',
          'technical_failure_assignment_reads_back_as_technical_failure',
          'technical_failure_session_reads_back_with_matching_ref',
        ],
        total_recovery_elapsed_ms: verificationEndMs - injectedFaultStartMs,
        fault_counter_observations: counter.attempts,
        fault_fired_count: faultFiredCount,
        matrix_prefix: prefix,
        secondary_assignment_id: techFailureAssignmentId,
      },
    }),
    missingAssignmentId,
    techFailureAssignmentId,
    techFailureSessionId: techFailureSession.session_id,
  };
}

// ---------------------------------------------------------------------------
// FAMILY 7-NARROW — raw-evidence integrity verification after recovery
// (scoped strictly to the identifiers produced by families 1/2/3/5/6 in
// THIS matrix run; no generalized/table-wide metric recomputation — that is
// FAMILY 7-FULL, explicitly deferred).
// ---------------------------------------------------------------------------

async function runFamily7Narrow(prefix, priorResults) {
  const { family2, family5, family6 } = priorResults;

  const injectedFaultStartMs = harness.nowMs();
  const injectedFaultStart = harness.isoNow();
  const counter = harness.createFaultCounter(1);
  const faultyPool = harness.wrapPoolWithFaults(pool, {
    matcher: /SELECT\s+\(SELECT is_nullable FROM information_schema\.columns/i,
    counter,
  });

  // F2 correction: the previous version of this check ran a LEFT JOIN
  // looking for evidence_attempts rows with no matching
  // evidence_assignments/evidence_sessions row. That query is tautological
  // — assignment_id and session_id are both NOT NULL with FK constraints on
  // evidence_attempts, so a committed orphan row is structurally impossible
  // and the query could only ever return zero rows. Presenting that as a
  // dynamic orphan-integrity verification would overclaim what was tested.
  // What is honestly verifiable, and is verified here, is that the REAL
  // constraints which make orphan rows impossible are actually present in
  // the LIVE schema (a live PostgreSQL catalog query, not a hardcoded
  // assumption) — a schema-safety assertion, not an "orphan observed" claim.
  const scopedAttemptIds = [family2.attemptId, family5.attemptId];
  const schemaConstraintCheckSql = "SELECT "
    + "(SELECT is_nullable FROM information_schema.columns WHERE table_name = 'evidence_attempts' AND column_name = 'assignment_id') AS assignment_id_nullable, "
    + "(SELECT is_nullable FROM information_schema.columns WHERE table_name = 'evidence_attempts' AND column_name = 'session_id') AS session_id_nullable, "
    + "(SELECT count(*) FROM pg_constraint WHERE conname = 'evidence_attempts_assignment_fk') AS assignment_fk_count, "
    + "(SELECT count(*) FROM pg_constraint WHERE conname = 'evidence_attempts_session_fk') AS session_fk_count";

  const { result: constraintResult, trace } = await harness.runWithHarnessRecovery({
    operation: () => faultyPool.query(schemaConstraintCheckSql),
    maxAttempts: HARNESS_INPUTS.maxAttempts,
    spacingMs: HARNESS_INPUTS.spacingMs,
    cadenceMode: HARNESS_INPUTS.cadenceMode,
  });
  const firstSuccess = trace.find((entry) => entry.recovery_succeeded);
  const healthyAtMs = firstSuccess.recovery_attempt_at_ms;
  const faultFiredCount = assertFaultFired(trace, counter, 1, 'FAMILY_7_NARROW');

  const verificationStart = harness.isoNow();
  const verificationStartMs = harness.nowMs();

  const constraintRow = constraintResult.rows[0];
  const constraintsGuaranteeNoOrphans = constraintRow.assignment_id_nullable === 'NO'
    && constraintRow.session_id_nullable === 'NO'
    && Number(constraintRow.assignment_fk_count) === 1
    && Number(constraintRow.session_fk_count) === 1;

  // Narrow duplicate-state re-check (scoped to family 5's assignment).
  const family5DuplicateCount = await countRows(
    pool,
    'evidence_attempts',
    'assignment_id = $1',
    [family5.assignmentId]
  );

  // Narrow contamination re-check: family 2's rolled-back first insert
  // attempt must not have left a surviving finalization row.
  const family2FinalizationCount = await countRows(
    pool,
    'evidence_attempt_finalizations',
    'attempt_id = $1',
    [family2.attemptId]
  );

  // Narrow classification re-check (family 6 unchanged by later episodes).
  const { rows: classificationRows } = await pool.query(
    `SELECT assignment_id, terminal_outcome FROM evidence_assignments
      WHERE assignment_id = ANY($1)`,
    [[family6.missingAssignmentId, family6.techFailureAssignmentId]]
  );
  const classificationById = new Map(
    classificationRows.map((row) => [row.assignment_id, row.terminal_outcome])
  );
  const classificationStillCorrect = classificationById.get(family6.missingAssignmentId) === 'MISSING'
    && classificationById.get(family6.techFailureAssignmentId) === 'TECHNICAL_FAILURE';

  // Narrow digest/version-consistency check: non-empty, non-corrupted
  // digest bookkeeping columns on the rows this run actually created.
  // Structural presence only — recomputing/re-hashing payload bytes is the
  // FAMILY 7-FULL generalized scope, explicitly deferred here.
  const { rows: digestRows } = await pool.query(
    `SELECT digest_algorithm, normalization_version, finalization_payload_digest
       FROM evidence_attempt_finalizations WHERE attempt_id = $1`,
    [family2.attemptId]
  );
  const digestConsistent = Boolean(
    digestRows[0]
    && digestRows[0].digest_algorithm
    && digestRows[0].normalization_version
    && digestRows[0].finalization_payload_digest
  );

  const contaminationDetected = !constraintsGuaranteeNoOrphans
    || family5DuplicateCount !== 1
    || family2FinalizationCount !== 1;
  const missingAmbiguityDetected = !classificationStillCorrect;
  const integrityPass = !contaminationDetected && !missingAmbiguityDetected && digestConsistent;

  const verificationEnd = harness.isoNow();
  const verificationEndMs = harness.nowMs();

  harness.assertCausalOrder([
    { name: 'injected_fault_start', value: injectedFaultStartMs },
    { name: 'first_recovery_attempt_at', value: trace[0].recovery_attempt_at_ms },
    { name: 'healthy_at', value: healthyAtMs },
    { name: 'integrity_verification_start_at', value: verificationStartMs },
    { name: 'integrity_verified_at', value: verificationEndMs },
  ]);

  return buildEpisode({
    failure_family: 'FAMILY_7_NARROW_RAW_EVIDENCE_INTEGRITY',
    affected_scope: 'raw evidence rows created by families 1/2/3/5/6 in this matrix run (scoped, not table-wide)',
    attempt_id: null,
    session_id: null,
    assignment_id: null,
    fault_duration_ms: 0,
    healthy_at: new Date(healthyAtMs).toISOString(),
    retry_attempt_spacing_ms: HARNESS_INPUTS.spacingMs,
    recovery_attempt_ordinal: trace.length,
    recovery_attempt_at: trace.map((e) => e.recovery_attempt_at),
    recovery_succeeded: true,
    error_class: trace[0].error_class,
    recovery_detection_latency_ms: healthyAtMs - injectedFaultStartMs,
    integrity_verification_latency_ms: verificationEndMs - verificationStartMs,
    integrity_verification_result: integrityPass ? 'PASS' : 'FAIL',
    duplicate_detected: family5DuplicateCount !== 1,
    contamination_detected: contaminationDetected,
    missing_ambiguity_detected: missingAmbiguityDetected,
    diagnostic: {
      retry_cadence_mode: HARNESS_INPUTS.cadenceMode,
      fault_recoverability_state_by_attempt: trace.map((e) => e.fault_recoverability_state),
      injected_fault_start: injectedFaultStart,
      first_recovery_attempt_at: trace[0].recovery_attempt_at,
      integrity_verification_start_at: verificationStart,
      integrity_verified_at: verificationEnd,
      fixture_scale: FIXTURE_SCALE,
      integrity_check_set: [
        // Live-schema constraint presence check (NOT a dynamic orphan
        // observation — a committed orphan row is structurally impossible
        // under these constraints, so no "orphan observed/verified" claim
        // is made; this confirms the constraints that make it impossible
        // are actually present in the live schema).
        'live_schema_constraint_presence_check(evidence_attempts.assignment_id/session_id NOT NULL + FK to evidence_assignments/evidence_sessions)',
        'scoped_duplicate_row_count(evidence_attempts)',
        'scoped_rollback_leftover_check(evidence_attempt_finalizations)',
        'scoped_classification_stability_check(evidence_assignments)',
        'scoped_digest_field_presence_check(evidence_attempt_finalizations)',
      ],
      total_recovery_elapsed_ms: verificationEndMs - injectedFaultStartMs,
      fault_counter_observations: counter.attempts,
      fault_fired_count: faultFiredCount,
      matrix_prefix: prefix,
      scoped_attempt_ids: scopedAttemptIds,
      schema_constraints_guarantee_no_orphans: constraintsGuaranteeNoOrphans,
    },
  });
}

// ---------------------------------------------------------------------------
// Full required family matrix (1, 2, 3, 5, 6, 7-narrow). FAMILY 4 and
// FAMILY 7-FULL are never called from here — see the deferral test below.
// ---------------------------------------------------------------------------

async function runFullMatrix(runIndex, sink) {
  const prefix = `B3M1_R${runIndex}_${harness.randomSuffix().toUpperCase()}`;
  const fixture = await setupAuthorityFixture(prefix);

  const episode1 = await runFamily1(fixture, prefix);
  const family2Result = await runFamily2(fixture, prefix);
  const episode3 = await runFamily3(prefix);
  const family5Result = await runFamily5(fixture, prefix);
  const family6Result = await runFamily6(fixture, prefix);
  const episode7Narrow = await runFamily7Narrow(prefix, {
    family2: family2Result,
    family5: family5Result,
    family6: family6Result,
  });

  const episodes = {
    family1: episode1,
    family2: family2Result.episode,
    family3: episode3,
    family5: family5Result.episode,
    family6: family6Result.episode,
    family7narrow: episode7Narrow,
  };

  for (const episode of Object.values(episodes)) {
    sink.emit(episode);
  }

  const classificationSummary = Object.fromEntries(
    Object.entries(episodes).map(([key, episode]) => [key, classificationOf(episode)])
  );

  return { prefix, episodes, classificationSummary };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('B-3 M1 incident recovery calibration', () => {
  let sink;
  let run1;
  let run2;

  before(async () => {
    await runMigrations();
    sink = harness.createEpisodeSink();
    run1 = await runFullMatrix(1, sink);
    run2 = await runFullMatrix(2, sink);
  });

  after(async () => {
    // F4 correction: clean up the ephemeral episode-package temp file after
    // this describe block's own tests (including the one that validates its
    // existence and location) have finished running. Only the exact
    // harness-created path is ever removed; absence is tolerated rather than
    // treated as a failure, since a cleanup pass should not itself become a
    // second point of failure.
    try {
      if (sink && sink.filePath && fs.existsSync(sink.filePath)) {
        fs.unlinkSync(sink.filePath);
      }
    } catch {
      // Best-effort cleanup of a harness-owned temp file; never fails the
      // suite over it.
    }
    await pool.end();
  });

  test('FAMILY 1 (transient DB read failure): recovers via harness retry against actual PostgreSQL with rollback-free read integrity', () => {
    const episode = run1.episodes.family1;
    assert.equal(episode.failure_family, 'FAMILY_1_TRANSIENT_READ');
    assert.equal(episode.recovery_succeeded, true);
    assert.equal(episode.integrity_verification_result, 'PASS');
    assert.ok(episode.recovery_attempt_ordinal >= 2, 'must have needed at least one injected failure + one recovery');
  });

  test('FAMILY 2 (transient DB write/transaction failure): actual PostgreSQL transaction rollback correctness holds under harness retry', () => {
    const episode = run1.episodes.family2;
    assert.equal(episode.failure_family, 'FAMILY_2_TRANSIENT_WRITE');
    assert.equal(episode.recovery_succeeded, true);
    assert.equal(episode.integrity_verification_result, 'PASS');
    assert.equal(episode.contamination_detected, false);
    // F1 correction: fault-fired proof, not merely final-state inference —
    // a matcher/SQL drift that silenced injection would fail this.
    assert.equal(episode.diagnostic.fault_fired_count, 1);
    assert.ok(episode.recovery_attempt_ordinal > 1);
  });

  test('FAMILY 3 (DB connection/backend unavailable then restored): isolated harness-owned backend termination and reconnection against actual PostgreSQL', () => {
    const episode = run1.episodes.family3;
    assert.equal(episode.failure_family, 'FAMILY_3_CONNECTION_UNAVAILABLE_THEN_RESTORED');
    assert.equal(episode.recovery_succeeded, true);
    assert.equal(episode.integrity_verification_result, 'PASS');
    assert.ok(episode.diagnostic.reconnected_pid !== episode.diagnostic.original_pid);
  });

  test('FAMILY 5 (duplicate logical attempt / idempotency interaction): replay and conflict correctness hold across a harness-retried recovery', () => {
    const episode = run1.episodes.family5;
    assert.equal(episode.failure_family, 'FAMILY_5_DUPLICATE_IDEMPOTENCY_INTERACTION');
    assert.equal(episode.duplicate_detected, true);
    assert.equal(episode.integrity_verification_result, 'PASS');
    assert.equal(episode.contamination_detected, false);
    assert.equal(episode.diagnostic.fault_fired_count, 1);
    assert.ok(episode.recovery_attempt_ordinal > 1);
  });

  test('FAMILY 6 (missing / technical-failure classification integrity): MISSING and TECHNICAL_FAILURE stay distinguishable through fault/recovery', () => {
    const episode = run1.episodes.family6;
    assert.equal(episode.failure_family, 'FAMILY_6_MISSING_VS_TECHNICAL_FAILURE_CLASSIFICATION');
    assert.equal(episode.missing_ambiguity_detected, false);
    assert.equal(episode.integrity_verification_result, 'PASS');
    assert.equal(episode.diagnostic.fault_fired_count, 1);
    assert.ok(episode.recovery_attempt_ordinal > 1);
  });

  test('FAMILY 7-NARROW (raw-evidence integrity verification after recovery): scoped duplicate/rollback/classification/digest-presence checks pass, and live-schema constraints that make committed orphans structurally impossible are confirmed present (not a dynamic orphan observation)', () => {
    const episode = run1.episodes.family7narrow;
    assert.equal(episode.failure_family, 'FAMILY_7_NARROW_RAW_EVIDENCE_INTEGRITY');
    assert.equal(episode.contamination_detected, false);
    assert.equal(episode.missing_ambiguity_detected, false);
    assert.equal(episode.integrity_verification_result, 'PASS');
    assert.equal(episode.diagnostic.schema_constraints_guarantee_no_orphans, true);
    assert.equal(episode.diagnostic.fault_fired_count, 1);
    assert.ok(episode.recovery_attempt_ordinal > 1);
  });

  test('FAMILY 4 (cascade_jobs worker/job processing) and FAMILY 7-FULL (generalized metric/recomputation) are absent/deferred, not implemented', () => {
    const familyKeys = Object.keys(run1.episodes);
    assert.deepEqual(
      familyKeys.sort(),
      ['family1', 'family2', 'family3', 'family5', 'family6', 'family7narrow'].sort()
    );
    for (const episode of Object.values(run1.episodes)) {
      assert.doesNotMatch(episode.failure_family, /FAMILY_4|CASCADE_JOB|WORKER/i);
      assert.doesNotMatch(episode.failure_family, /FAMILY_7_FULL|GENERALIZED/i);
    }
    // Functional-usage check — not a string-absence check on this file's own
    // deferral documentation (which legitimately names FAMILY 4 and
    // FAMILY 7-FULL above, in comments and this test's title, to record that
    // they are deferred). What must actually be absent is any SQL statement
    // touching the cascade_jobs table and any worker/job-processing module.
    const ownSource = fs.readFileSync(__filename, 'utf8');
    assert.doesNotMatch(ownSource, /(FROM|INTO|UPDATE|JOIN)\s+cascade_jobs/i);
    assert.doesNotMatch(ownSource, /require\(['"][^'"]*worker[^'"]*['"]\)/i);
  });

  test('repeatability smoke check: two full-matrix executions under identical declared harness inputs produce matching integrity classifications', () => {
    assert.notEqual(run1.prefix, run2.prefix, 'the two executions must use independent fixtures');
    for (const key of Object.keys(run1.classificationSummary)) {
      const a = run1.classificationSummary[key];
      const b = run2.classificationSummary[key];
      assert.deepEqual(
        a,
        b,
        `integrity classification for ${key} differs between the two executions — ` +
          'this is a harness/evidence reliability failure requiring investigation, ' +
          'not an expected outcome under matching declared inputs'
      );
    }
    // Matching classifications across these two executions is OBSERVED
    // REPEATABILITY FOR THESE EXECUTIONS ONLY. It does not prove harness
    // determinism, absence of nondeterminism, recovery-time distribution
    // stability, or owner-policy adequacy.
  });

  test('timing internal consistency: every emitted episode is causally ordered and non-negative; ordinary jitter is not a failure', () => {
    for (const run of [run1, run2]) {
      for (const episode of Object.values(run.episodes)) {
        assert.ok(episode.recovery_detection_latency_ms >= 0);
        assert.ok(episode.integrity_verification_latency_ms >= 0);
        assert.ok(episode.diagnostic.total_recovery_elapsed_ms >= 0);
        for (const at of episode.recovery_attempt_at) {
          assert.ok(new Date(at).getTime() >= new Date(episode.diagnostic.injected_fault_start).getTime());
        }
        // Two runs are never asserted to have EQUAL timing values — only
        // causal ordering and non-negativity are required. Latency jitter
        // between run1 and run2 is expected and is not itself a failure.
      }
    }
  });

  test('no human data, no actual-provider calls, no raw audio are used by this calibration harness', () => {
    const ownFiles = [
      __filename,
      path.resolve(__dirname, 'incidentRecoveryCalibrationHarness.js'),
    ];
    for (const filePath of ownFiles) {
      // Exclude this self-check's own lines: the forbidden-term patterns
      // necessarily contain the very words they search for, which would
      // otherwise make this scan match itself.
      const source = fs.readFileSync(filePath, 'utf8')
        .split('\n')
        .filter((line) => !line.includes('SELF_CHECK_EXCLUDE'))
        .join('\n');
      assert.doesNotMatch(source, /openai|anthropic\.com\/v1|whisper|speech-to-text|elevenlabs/i); // SELF_CHECK_EXCLUDE
      assert.doesNotMatch(source, /rawAudio|audioBuffer|\.wav['"]|\.mp3['"]/i); // SELF_CHECK_EXCLUDE
      assert.doesNotMatch(source, /humanParticipantData|mturk|prolific/i); // SELF_CHECK_EXCLUDE
    }
  });

  test('ephemeral evidence package: every required episode field is present and packages are not committed', () => {
    for (const run of [run1, run2]) {
      for (const episode of Object.values(run.episodes)) {
        for (const key of REQUIRED_EPISODE_KEYS) {
          assert.ok(
            Object.prototype.hasOwnProperty.call(episode, key),
            `episode missing required field: ${key}`
          );
        }
      }
    }
    assert.ok(fs.existsSync(sink.filePath), 'episode sink file must exist under the OS temp directory');
    const tmpDir = require('node:os').tmpdir();
    assert.ok(
      path.resolve(sink.filePath).startsWith(path.resolve(tmpDir)),
      'episode package file must live under the OS temp directory, never inside the repository'
    );
    const repoRoot = path.resolve(__dirname, '..');
    assert.ok(
      !path.resolve(sink.filePath).startsWith(repoRoot),
      'episode package file must not be written inside the repository worktree'
    );
  });
});
